version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 7.0.0-alpha05
    - 7.0.0-alpha07
    - 7.0.0-alpha08
    - 7.0.0-alpha09
    - 7.0.0-alpha10
    - 7.0.0-alpha11
  - dependency-name: androidx.appcompat:appcompat
    versions:
    - 1.2.0
  - dependency-name: com.google.android.material:material
    versions:
    - 1.3.0-rc01
  - dependency-name: junit:junit
    versions:
    - 4.13.1
